version: '3.8'

services:
  radar-precos:
    build: .
    container_name: radar_precos
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./price_hunter.db:/app/price_hunter.db

